const DEFAULT_CHANNEL=process.env.SOOP_CHANNEL||'chunbongtv';const DEFAULT_POST=process.env.SOOP_POST||'204274449';const MAX_PAGES=Math.max(1,Math.min(200,Number(process.env.MAX_PAGES||100)));
const SCORE_PATHS=['up_count','up_cnt','up','like_count','like_cnt','like_num','likes','like','recommend_count','recommend_cnt','recommend_num','recommend','recommendation_count','vote_count','vote_cnt','votes','good_count','good_cnt','good_num','good','memo_like_count','memo_like_cnt','comment_like_count','comment_like_cnt','comment_like_num','comment_recommend_count','comment_recommend_cnt','comment_recommend_num','p_comment_like_count','p_comment_like_cnt','p_comment_like_num','p_recommend_count','p_recommend_cnt','p_recommend_num'];
function num(v){if(typeof v==='number'&&Number.isFinite(v))return v;if(typeof v==='string'){const n=Number(v.replace(/,/g,'').trim());if(Number.isFinite(n))return n}return null}
function score(c){for(const k of SCORE_PATHS){const n=num(c?.[k]);if(n!==null)return{score:n,field:k}}const found=[];const walk=(o,p='',d=0)=>{if(!o||typeof o!=='object'||d>3)return;for(const[k,v]of Object.entries(o)){const q=p?`${p}.${k}`:k,lk=k.toLowerCase(),nv=num(v);if(nv!==null&&/(^|_)(up|like|recommend|recommendation|vote|good)(_|$)/.test(lk)&&!/(is_|yn|_yn|user|reply|date|time|no$|id$)/.test(lk))found.push({q,n:nv,w:/(count|cnt|num|total|score)/.test(lk)?20:10});else if(v&&typeof v==='object'&&!Array.isArray(v))walk(v,q,d+1)}};walk(c);found.sort((a,b)=>b.w-a.w||b.n-a.n);return found[0]?{score:found[0].n,field:found[0].q}:{score:0,field:null}}
function first(o,ks,f=''){for(const k of ks)if(o?.[k]!==undefined&&o?.[k]!==null&&o?.[k]!=='')return o[k];return f}function strip(s){return String(s??'').replace(/<br\s*\/?>/gi,'\n').replace(/<[^>]*>/g,'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#39;/gi,"'").replace(/&quot;/gi,'"').trim()}
function norm(c,postUrl){const x=score(c),id=String(first(c,['p_comment_no','comment_no','memo_no','id','no'],'')),userId=String(first(c,['user_id','userid','userId','writer_id','member_id'],'')),nickname=String(first(c,['user_nick','nickname','user_name','nick','writer_nick','name'],userId||'알 수 없음')),content=strip(first(c,['comment','contents','content','memo','text','body','comment_content'],'')),date=String(first(c,['reg_date','register_date','created_at','createdAt','date','write_date'],''));return{id,userId,nickname,content,date,up:x.score,upField:x.field,link:id?`${postUrl}#comment_noti${id}`:postUrl}}
async function json(url){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),12000);try{const r=await fetch(url,{headers:{accept:'application/json, text/plain, */*','accept-language':'ko-KR,ko;q=0.9,en;q=0.8','user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36',referer:'https://www.sooplive.com/',origin:'https://www.sooplive.com'},signal:ctl.signal});if(!r.ok)throw new Error(`SOOP API HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
async function pages(channel,post,orderby){const all=[];let page=1,last=1,meta={};while(page<=last&&page<=MAX_PAGES){const u=`https://chapi.sooplive.co.kr/api/${encodeURIComponent(channel)}/title/${encodeURIComponent(post)}/comment?page=${page}&orderby=${encodeURIComponent(orderby)}`;const j=await json(u),data=Array.isArray(j?.data)?j.data:[];all.push(...data);meta=j?.meta||meta;const lp=Number(j?.meta?.last_page??1);last=Number.isFinite(lp)&&lp>0?lp:1;if(!data.length)break;page++}return{all,meta,last}}
function idOf(c){return String(first(c,['p_comment_no','comment_no','memo_no','id','no'],''))}
function sameOrder(a,b,n=30){const aa=a.slice(0,n).map(idOf),bb=b.slice(0,n).map(idOf);return aa.length===bb.length&&aa.every((x,i)=>x===bb[i])}
function descQuality(raw){const vals=raw.slice(0,50).map(c=>score(c).score);let pairs=0,ok=0;for(let i=1;i<vals.length;i++){pairs++;if(vals[i-1]>=vals[i])ok++}return pairs?ok/pairs:0}
async function load(channel,post){const chronological=await pages(channel,post,'reg_date');const candidates=[];for(const ord of ['like','up','recommend']){try{const r=await pages(channel,post,ord);candidates.push({ord,...r,quality:descQuality(r.all),different:!sameOrder(chronological.all,r.all)})}catch{}}
let chosen=candidates.sort((a,b)=>(Number(b.different)-Number(a.different))||(b.quality-a.quality)||(['like','up','recommend'].indexOf(a.ord)-['like','up','recommend'].indexOf(b.ord)))[0];if(!chosen)chosen={ord:'reg_date',all:chronological.all,quality:0,different:false};
const postUrl=`https://www.sooplive.com/station/${channel}/post/${post}`;const base=chronological.all.map(c=>norm(c,postUrl));const rankIds=new Map(chosen.all.map((c,i)=>[idOf(c),i+1]));const comments=base.map(c=>({...c,upRank:rankIds.get(c.id)||null}));if(!chosen.different){comments.sort((a,b)=>Number(b.up)-Number(a.up)||new Date(a.date)-new Date(b.date));comments.forEach((c,i)=>c.upRank=i+1)}
return{comments,meta:chronological.meta,lastPage:chronological.last,scoreFields:[...new Set(comments.map(c=>c.upField).filter(Boolean))],rankingSource:chosen.different?`SOOP ${chosen.ord} 순`:'UP 수치 직접 정렬',postUrl}}
module.exports=async function(req,res){res.setHeader('Cache-Control','no-store, max-age=0');res.setHeader('Access-Control-Allow-Origin','*');if(req.method==='OPTIONS')return res.status(204).end();const channel=String(req.query.channel||DEFAULT_CHANNEL).trim(),postId=String(req.query.post||DEFAULT_POST).trim();if(!/^[a-zA-Z0-9_-]+$/.test(channel)||!/^\d+$/.test(postId))return res.status(400).json({ok:false,error:'잘못된 채널 또는 게시글 번호입니다.'});try{return res.status(200).json({ok:true,channel,postId,fetchedAt:new Date().toISOString(),...(await load(channel,postId))})}catch(e){return res.status(502).json({ok:false,channel,postId,error:e?.message||String(e)})}}
